version: '2'

services:
  samba:
    image: yuri1987/samba-docker
    container_name: samba
    volumes:
    - /media:/yourdir
    environment:
    - USER=youruser
    - PASS=yourpass
    - STORAGE=/yourdir
    - WORKGROUP=yourworkgroup
    restart: always
    network_mode: host
    tty: true
